language: php

php: 
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
